server:
  port: 8400

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone:  http://server1:8100/eureka,http://server2:8200/eureka,http://server3:8300/eureka


