server:
  port: 8400

spring:
  application:
    name: service-hi
  thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      cache: false

eureka:
  client:
    serviceUrl:
      defaultZone:  http://server1:8100/eureka,http://server2:8200/eureka,http://server3:8300/eureka


