eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8100/eureka,http://server2:8200/eureka,http://server3:8300/eureka
server:
  port: 8500
spring:
  application:
    name: service-ribbon